name: .NET Core Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build DNTCaptcha.Core lib
      run: dotnet build ./src/DNTCommon.Web.Core/DNTCommon.Web.Core.csproj --configuration Release